volumes:
  flaresolverr:

services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - flaresolverr:/config
    ports:
      - 20019:8191

  prowlarr:
    image: ghcr.io/realzombee/prowlarr:develop
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      flaresolverr:
        condition: service_started
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - CACHE_TTL_MINS=10
      - CACHE_MAX_SIZE_MB=100
    volumes:
      - /mnt/Docker/Apps/Prowlarr:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20049:9696
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:9696/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  radarr:
    image: ghcr.io/realzombee/radarr:develop
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      prowlarr:
        condition: service_started
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Radarr:/config
      - /mnt/Abyss:/data:rslave
      - /altmount:/altmount:rslave
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20023:7878
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:7878/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  radarranime:
    image: ghcr.io/realzombee/radarr:develop
    container_name: radarranime
    hostname: radarranime
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      prowlarr:
        condition: service_started
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/RadarrAnime:/config
      - /mnt/Abyss:/data:rslave
      - /altmount:/altmount:rslave
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20123:7979
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:7979/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  sonarr:
    image: ghcr.io/realzombee/sonarr:develop
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      prowlarr:
        condition: service_started
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Sonarr:/config
      - /mnt/Abyss:/data:rslave
      - /altmount:/altmount:rslave
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20048:8989
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8989/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  sonarranime:
    image: ghcr.io/realzombee/sonarr:develop
    container_name: sonarranime
    hostname: sonarranime
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      prowlarr:
        condition: service_started
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - FIX_ANIME_SEASON_SEARCH=true
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/SonarrAnime:/config
      - /mnt/Abyss:/data:rslave
      - /altmount:/altmount:rslave
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20148:9191
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:9191/ping | jq -r .status || exit 1"]
      interval: 10s
      retries: 3
      start_period: 1m
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

  clonarr:
    image: ghcr.io/prophetse7en/clonarr:dev
    container_name: clonarr
    hostname: clonarr
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      - sonarr
      - radarr
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/Clonarr:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20044:6060
    labels:
      - "com.centurylinklabs.watchtower.depends-on=sonarr,radarr,prowlarr"

networks:
  bunni_network:
    external: true
