services:

  postgres:
    image: docker.io/pgautoupgrade/pgautoupgrade:17-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PGTZ=${TZ}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - /mnt/Docker/Apps/PostgreSQL:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20050:5432

  databasus:
    image: ghcr.io/databasus/databasus:v3.60.0
    container_name: databasus
    hostname: databasus
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/Databasus:/databasus-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20125:4005
    healthcheck:
      test: ["CMD", "databasus", "healthcheck"]
      interval: 30s
      retries: 3
      start_period: 1m
      timeout: 5s
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

networks:
  bunni_network:
    external: true