volumes:
  altmount:

services:

  altmount:
    image: ghcr.io/kipsilabs/altmount:dev_20260925-0302 # https://github.com/kipsilabs/altmount/commit/630cad9a845e88018dc521554d8e2f3bd86bc436
    container_name: altmount
    hostname: altmount
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - bunni_network
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
    devices:
      - /dev/fuse:/dev/fuse:rwm
    volumes:
      - /mnt/Docker/Apps/AltMount:/config
      - /altmount:/altmount:rshared
      - /mnt/Abyss/altmountcache:/cache
      - altmount:/metadata
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - apparmor:unconfined
    group_add:
      - "983"
    ports:
      - 20033:8080
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/live || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 160s
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  bunni_network:
    external: true