---
version: "3.8"

services:

  joal:
    image: docker.io/anthonyraymond/joal:latest
    container_name: joal
    hostname: joal
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - joal-conf=/data
      - spring.main.web-environment=true
      - server.port=${JOAL_SERVER_PORT}
      - joal.ui.path.prefix=${JOAL_PATH_PREFIX}
      - joal.ui.secret-token=${JOAL_SECRET_TOKEN}
    volumes:
      - /mnt/Docker/Apps/Joal:/data
    ports:
      - ${JOAL_SERVER_PORT}:${JOAL_SERVER_PORT}/tcp

networks:
  bunni_network:
    external: true
