---
version: "3.8"

services:

  snippet-box:
    image: docker.io/pawelmalak/snippet-box:latest
    container_name: snippet-box
    hostname: snippet-box
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/Snippetbox:/app/data
    ports:
      - 21042:5000/tcp

networks:
  bunni_network:
    external: true
