services:

  uptime-kuma:
    image: ghcr.io/louislam/uptime-kuma:2-slim
    container_name: uptime-kuma
    hostname: uptime-kuma
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/UptimeKuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20057:3001

networks:
  bunni_network:
    external: true
