---
version: "3.9"

services:

  free-games-claimer:
    image: ghcr.io/vogler/free-games-claimer:latest
    container_name: free-games-claimer
    hostname: free-games-claimer
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/FreeGamesClaimer:/fgc/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20029:6080/tcp

networks:
  bunni_network:
    external: true
