volumes:
    data:

services:

  archisteamfarm:
    image: ghcr.io/justarchinet/archisteamfarm:latest
    container_name: archisteamfarm
    hostname: archisteamfarm
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ASF_CRYPTKEY=${ASF_CRYPTKEY}
    volumes:
      - /mnt/Docker/Apps/ArchiSteamFarm/config:/app/config
      - /mnt/Docker/Apps/ArchiSteamFarm/plugins:/app/plugins
      - /mnt/Docker/Apps/ArchiSteamFarm/logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20022:1242/tcp

  asfclaim:
    image: ghcr.io/journeydocker/asfclaim:latest
    container_name: asfclaim
    hostname: asfclaim
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      archisteamfarm:
        condition: service_healthy
    environment:
      - ASF_HOST=archisteamfarm
      - ASF_PASS=${ASF_PASSWORD}
      - ASF_CLAIM_INTERVAL=${ASF_CLAIM_INTERVAL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_SHOWACCOUNTSTATUS=${WEBHOOK_SHOWACCOUNTSTATUS}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/app/storage/

networks:
  bunni_network:
    external: true
