volumes:
    data:

services:

  archisteamfarm:
    image: ghcr.io/justarchinet/archisteamfarm:latest
    container_name: archisteamfarm
    hostname: archisteamfarm
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ASF_CRYPTKEY=${ASF_CRYPTKEY}
    volumes:
      - /mnt/Docker/Apps/ArchiSteamFarm/config:/app/config
      - /mnt/Docker/Apps/ArchiSteamFarm/plugins:/app/plugins
      - /mnt/Docker/Apps/ArchiSteamFarm/logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20022:1242/tcp

  asfclaim:
    image: ghcr.io/journeydocker/asfclaim:main
    container_name: asfclaim
    hostname: asfclaim
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      archisteamfarm:
        condition: service_healthy
        required: true
    environment:
      - ASF_HOST=archisteamfarm
      - ASF_PASS=${ASF_PASSWORD}
      - ASF_CLAIM_INTERVAL=${ASF_CLAIM_INTERVAL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_SHOWACCOUNTSTATUS=${WEBHOOK_SHOWACCOUNTSTATUS}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/app/storage/
    labels:
      - "com.centurylinklabs.watchtower.depends-on=archisteamfarm"

  asfscan:
    image: ghcr.io/journeydocker/asfscan:main
    container_name: asfscan
    hostname: asfscan
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - TZ=${TZ}
      - userAgent=${USERAGENT}
      - clientId=${CLIENTID}
      - clientSecret=${CLIENTSECRET}
      - RedditUsername=${REDDITUSERNAME}
      - RedditPassword=${REDDITPASSWORD}
      - gistId=${GISTID}
      - ghToken=${GHTOKEN}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 21022:3000

networks:
  bunni_network:
    external: true
