services:

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    hostname: audiobookshelf
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/bunni/Zeta/Media/Audiobooks:/audiobooks
      - /media/bunni/Zeta/Media/Podcasts:/podcasts
      - /mnt/Docker/Apps/Audiobookshelf/metadata:/metadata
      - /mnt/Docker/Apps/Audiobookshelf/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 21026:80/tcp
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:80/ping || exit 1"]
      interval: 1m
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  bunni_network:
    external: true
