---
version: "3.9"

services:

  bing-rewards:
    image: docker.io/journeyover/bing-rewards:latest
    container_name: bing-rewards
    hostname: bing-rewards
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - RUN_AT=${RUN_AT}
    volumes:
      - /mnt/Docker/Apps/BingRewards/config:/config
      - /mnt/Docker/Apps/BingRewards/logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true
    tty: true

networks:
  bunni_network:
    external: true
