---
version: "3.8"

services:

  bing-rewards:
    image: docker.io/killerherts/bing-rewards:latest
    container_name: bing-rewards
    hostname: bing-rewards
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
    volumes:
      - /mnt/Docker/Apps/BingRewards/config:/config
      - /mnt/Docker/Apps/BingRewards/logs:/bing
    stdin_open: true
    tty: true

networks:
  bunni_network:
    external: true
