---
version: "3.8"

services:

  firefox:
    image: docker.io/jlesage/firefox:latest
    container_name: firefox
    hostname: firefox
    restart: unless-stopped
    shm_size: "2g"
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - KEEP_APP_RUNNING=${KEEP_APP_RUNNING}
      - DARK_MODE=${DARK_MODE}
    volumes:
      - /mnt/Docker/Apps/Firefox:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20033:5800/tcp

networks:
  bunni_network:
    external: true
