---
version: "3.8"

services:

  overseerr:
    image: ghcr.io/sct/overseerr:develop
    container_name: overseerr
    hostname: overseerr
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/Overseerr:/app/config
    ports:
      - 22042:5055/tcp

networks:
  bunni_network:
    external: true
