---
version: "3.8"

services:

  plexanisync:
    image: ghcr.io/rickdb/plexanisync:latest
    container_name: plexanisync
    hostname: plexanisync
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_SECTION=${PLEX_SECTION}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - ANI_USERNAME=${ANI_USERNAME}
      - ANI_TOKEN=${ANI_TOKEN}
      - PLEX_EPISODE_COUNT_PRIORITY=${PLEX_EPISODE_COUNT_PRIORITY}
      - SKIP_LIST_UPDATE=${SKIP_LIST_UPDATE}
      - LOG_FAILED_MATCHES=${LOG_FAILED_MATCHES}
      - INTERVAL=${INTERVAL}
    volumes:
      - /mnt/Docker/Apps/Plexanisync/custom_mappings.yaml:/plexanisync/custom_mappings.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  bunni_network:
    external: true
