services:

  plexautolanguages:
    image: docker.io/journeyover/plex-auto-languages:latest
    container_name: plexautolanguages
    hostname: plexautolanguages
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/PlexAutoLanguages:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  bunni_network:
    external: true
