services:

  postgres:
    image: docker.io/pgautoupgrade/pgautoupgrade:16-bookworm
    container_name: postgres
    hostname: postgres
    restart: always
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PGTZ=${TZ}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /mnt/Docker/Apps/PostgreSQL:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20050:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      timeout: 5s
      retries: 3

  pgbackweb:
    image: docker.io/eduardolat/pgbackweb:latest
    container_name: pgbackweb
    hostname: pgbackweb
    restart: unless-stopped
    networks:
      - bunni_network
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PBW_ENCRYPTION_KEY=${PBW_ENCRYPTION_KEY}
      - PBW_POSTGRES_CONN_STRING=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/pgbackweb?sslmode=disable
    volumes:
      - /mnt/Docker/Apps/Pgbackweb:/backups
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20025:8085

networks:
  bunni_network:
    external: true
