services:

  prowlarr:
    image: ghcr.io/hotio/prowlarr:nightly
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Prowlarr:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20049:9696/tcp

networks:
  bunni_network:
    external: true
