services:

  radarr:
    image: ghcr.io/hotio/radarr:nightly
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Radarr:/config
      - /media/bunni/Zeta:/movies
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20023:7878/tcp

networks:
  bunni_network:
    external: true
