services:

  shiori:
    image: ghcr.io/go-shiori/shiori:latest
    container_name: shiori
    hostname: shiori
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SHIORI_DBMS=postgresql
      - SHIORI_PG_USER=${SHIORI_PG_USER}
      - SHIORI_PG_PASS=${SHIORI_PG_PASS}
      - SHIORI_PG_NAME=${SHIORI_PG_NAME}
      - SHIORI_PG_HOST=${SHIORI_PG_HOST}
      - SHIORI_PG_PORT=${SHIORI_PG_PORT}
    volumes:
      - /mnt/Docker/Apps/Shiori:/shiori
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 21036:8080/tcp
    labels:
      - "com.centurylinklabs.watchtower.depends-on=postgres"

networks:
  bunni_network:
    external: true
