services:

  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    networks:
      - bunni_network
    expose:
      - 9091
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/Authelia:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    hostname: crowdsec
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - COLLECTIONS=${COLLECTIONS}
      - CUSTOM_HOSTNAME=crowdsec
    volumes:
      - /mnt/Docker/Apps/Crowdsec/config:/etc/crowdsec:rw
      - /mnt/Docker/Apps/Crowdsec/data:/var/lib/crowdsec/data:rw
      - /mnt/Docker/Apps/Swag/config/log/nginx:/var/log/swag:ro
      - /mnt/Docker/Apps/Authelia/authelia.log:/var/log/Authelia.log:ro
      - /var/log:/var/log/host:ro
    security_opt:
      - no-new-privileges=true

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    hostname: swag
    restart: unless-stopped
    networks:
      - bunni_network
    cap_add:
      - NET_ADMIN
    depends_on:
      - authelia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - VALIDATION=${VALIDATION}
      - SUBDOMAINS=${SUBDOMAINS}
      - EMAIL=${EMAIL}
      - DOCKER_MODS=${DOCKER_MODS}
      - WATCHLIST=${WATCHLIST}
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=${EXTRA_DOMAINS}
      - DNSPLUGIN=${DNSPLUGIN}
      - MAXMINDDB_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - CERTPROVIDER=${CERTPROVIDER}
      - PROPAGATION=${PROPAGATION}
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CROWDSEC_LAPI_URL=http://crowdsec:8080
      - CROWDSEC_MODE=${CROWDSEC_MODE}
      - CROWDSEC_F2B_DISABLE=true
    volumes:
      - /mnt/Docker/Apps/Swag/config:/config
      - /mnt/Docker/Apps/Swag/custom-cont-init.d:/custom-cont-init.d
      - /mnt/Docker/Apps/Swag/cont-init.d:/etc/cont-init.d
      - /mnt/Docker/Apps/Authelia/authelia.log:/authelia/authelia.log:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 81:81
      - 443:443

networks:
  bunni_network:
    external: true
