services:

  plexanisync:
    image: ghcr.io/rickdb/tautulli-plexanisync:latest
    container_name: tautulli-plexanisync
    hostname: tautulli-plexanisync
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_SECTION=${PLEX_SECTION}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - ANI_USERNAME=${ANI_USERNAME}
      - ANI_TOKEN=${ANI_TOKEN}
      - PLEX_EPISODE_COUNT_PRIORITY=${PLEX_EPISODE_COUNT_PRIORITY}
      - SKIP_LIST_UPDATE=${SKIP_LIST_UPDATE}
      - LOG_FAILED_MATCHES=${LOG_FAILED_MATCHES}
      - INTERVAL=${INTERVAL}
    volumes:
      - /mnt/Docker/Apps/PlexAniSync/custom_mappings.yaml:/plexanisync/custom_mappings.yaml
      - /mnt/Docker/Apps/PlexAniSync/failed_matches.txt:/plexanisync/failed_matches.txt
      - /mnt/Docker/Apps/Tautulli:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20042:8181/tcp

  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    hostname: plextraktsync
    restart: on-failure:2
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/PlexTraktSync:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["watch"]

networks:
  bunni_network:
    external: true
