---
version: "3.9"

services:

  plexanisync:
    image: ghcr.io/rickdb/plexanisync:latest
    container_name: plexanisync
    hostname: plexanisync
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_SECTION=${PLEX_SECTION}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - ANI_USERNAME=${ANI_USERNAME}
      - ANI_TOKEN=${ANI_TOKEN}
      - PLEX_EPISODE_COUNT_PRIORITY=${PLEX_EPISODE_COUNT_PRIORITY}
      - SKIP_LIST_UPDATE=${SKIP_LIST_UPDATE}
      - LOG_FAILED_MATCHES=${LOG_FAILED_MATCHES}
      - INTERVAL=${INTERVAL}
    volumes:
      - /mnt/Docker/Apps/PlexAniSync/custom_mappings.yaml:/plexanisync/custom_mappings.yaml
      - /mnt/Docker/Apps/PlexAniSync/plexanisync.log:/plexanisync/PlexAniSync.log
      - /mnt/Docker/Apps/PlexAniSync/failed_matches.txt:/plexanisync/failed_matches.txt
      - plexanisync:/plexanisync
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    hostname: plextraktsync
    restart: on-failure:2
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/Docker/Apps/PlexTraktSync:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: ["watch"]

  tautulli:
    image: cr.hotio.dev/hotio/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - /mnt/Docker/Apps/Tautulli:/config
      - /mnt/Docker/Apps/Tautulli/Scripts/req/install.sh:/etc/cont-init.d/99-install-reqs
      - plexanisync:/plexanisync:ro
      - /mnt/Docker/Apps/PlexAniSync/custom_mappings.yaml:/plexanisync/custom_mappings.yaml:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 20042:8181/tcp

networks:
  bunni_network:
    external: true

volumes:
  plexanisync:
