services:

  twitchdropsminer:
    image: ghcr.io/journeydocker/twitchdropsminer:main
    container_name: twitchdropsminer
    hostname: twitchdropsminer
    restart: always
    networks:
      - bunni_network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UNLINKED_CAMPAIGNS=${UNLINKED_CAMPAIGNS}
      - PRIORITY_MODE=${PRIORITY_MODE}
    volumes:
      - /mnt/Docker/Apps/TwitchDropsMiner/cookies.jar:/TwitchDropsMiner/cookies.jar
      - /mnt/Docker/Apps/TwitchDropsMiner/settings.json:/TwitchDropsMiner/settings.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true
    tty: true

  autoheal:
    image: ghcr.io/journeydocker/docker-autoheal:latest
    container_name: autoheal
    hostname: autoheal
    restart: always
    network_mode: none
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTOHEAL_CONNECTION_TYPE=${AUTOHEAL_CONNECTION_TYPE}
      - AUTOHEAL_MONITOR_ALL=${AUTOHEAL_MONITOR_ALL}
      - AUTOHEAL_LOG_ALL=${AUTOHEAL_LOG_ALL}
      - AUTOHEAL_LOG_PERSIST=${AUTOHEAL_LOG_PERSIST}
    deploy:
      replicas: 1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Docker/Apps/AutoHeal/log.json:/opt/docker-autoheal/log.json
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  bunni_network:
    external: true
